import ProductCard from "./ProductCard"; import SiteChrome from "./SiteChrome"; import CatalogControls from "./CatalogControls";
import { getBrands, getCategories, listOf, safeFetch } from "../lib/api"; import type { Paginated, Product } from "../lib/types";
type Params = Record<string, string | undefined>;
export default async function CatalogPage({ title, path = "/shop", params = {} }: { title: string; path?: string; params?: Params }) {
  const apiParams = new URLSearchParams(); Object.entries(params).forEach(([k, v]) => v && apiParams.set(k, v));
  const [products, categoriesRaw, brandsRaw] = await Promise.all([safeFetch<Paginated<Product>>(`/products/?${apiParams}`, { count: 0, next: null, previous: null, results: [] }), getCategories(), getBrands()]);
  const categories = listOf(categoriesRaw), brands = listOf(brandsRaw), page = Number(params.page || 1), pages = Math.max(1, Math.ceil(products.count / 12));
  const pageLink = (target: number) => { const next = new URLSearchParams(); Object.entries(params).forEach(([k, v]) => v && k !== "page" && next.set(k, v)); next.set("page", String(target)); return `${path}?${next}`; };
  const labels: Record<string,string> = { search: `جستجو: ${params.search || ""}`, category: categories.find(c=>c.slug===params.category)?.name || "دسته‌بندی", brand: brands.find(b=>b.slug===params.brand)?.name || "برند", min_price: `از ${new Intl.NumberFormat("fa-IR").format(Number(params.min_price||0))}`, max_price: `تا ${new Intl.NumberFormat("fa-IR").format(Number(params.max_price||0))}`, rating: `${params.rating}+ ستاره`, availability: "فقط موجودها", discount: "تخفیف‌دار" };
  const activeFilters = Object.keys(labels).filter(key => params[key]);
  const removeFilter = (key:string) => { const next=new URLSearchParams(); Object.entries(params).forEach(([k,v])=>v&&k!==key&&k!=="page"&&next.set(k,v)); return `${path}?${next}`; };
  return <SiteChrome><main className="shell catalogPage"><div className="catalogTitle"><div><span>فروشگاه جانِبی</span><h1>{title}</h1><p><b>{new Intl.NumberFormat("fa-IR").format(products.count)}</b> کالا با امکان مقایسه و خرید امن</p></div><div className="catalogDecor"><i></i><i></i><i></i></div></div>{activeFilters.length>0&&<div className="activeFilters"><span>فیلترهای فعال:</span>{activeFilters.map(key=><a href={removeFilter(key)} key={key}>{labels[key]} <b>×</b></a>)}<a className="clearAll" href="/shop">پاک کردن همه</a></div>}<div className="catalogWorkspace"><CatalogControls path={path} params={params} categories={categories} brands={brands}/><section className="catalogResults"><div className="resultSummary"><span>نمایش {new Intl.NumberFormat("fa-IR").format(products.results.length)} کالا در این صفحه</span><small>صفحه {new Intl.NumberFormat("fa-IR").format(page)} از {new Intl.NumberFormat("fa-IR").format(pages)}</small></div>{products.results.length ? <div className="productGrid">{products.results.map((p, i) => <ProductCard key={p.id} product={p} index={i}/>)}</div> : <div className="emptyState"><span>⌕</span><b>محصولی پیدا نشد</b><p>فیلترها را کمی بازتر کنید یا عبارت دیگری بنویسید.</p><a className="button primary" href="/shop">نمایش همه محصولات</a></div>}<div className="pagination"><a className={page <= 1 ? "disabled" : ""} href={pageLink(Math.max(1, page - 1))}>→ قبلی</a><div>{Array.from({ length: Math.min(5, pages) }, (_, i) => Math.max(1, Math.min(Math.max(1, pages - 4), page - 2)) + i).filter(n => n <= pages).map(n => <a className={n === page ? "active" : ""} href={pageLink(n)} key={n}>{new Intl.NumberFormat("fa-IR").format(n)}</a>)}</div><a className={page >= pages ? "disabled" : ""} href={pageLink(Math.min(pages, page + 1))}>بعدی ←</a></div></section></div></main></SiteChrome>;
}
