"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { Brand, Category } from "../lib/types";
type Params = Record<string, string | undefined>;
export default function CatalogControls({ path, params, categories, brands }: { path: string; params: Params; categories: Category[]; brands: Brand[] }) {
  const router = useRouter(); const [mobileOpen, setMobileOpen] = useState(false);
  function apply(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const next = new URLSearchParams(); form.forEach((value, key) => { if (String(value).trim()) next.set(key, String(value).trim()); }); if (params.ordering) next.set("ordering", params.ordering); router.push(`${path}?${next.toString()}`); setMobileOpen(false); }
  function sort(ordering: string) { const next = new URLSearchParams(); Object.entries(params).forEach(([k, v]) => v && k !== "page" && next.set(k, v)); next.set("ordering", ordering); router.push(`${path}?${next}`); }
  function clear() { router.push(path); setMobileOpen(false); }
  return <><button className="mobileFilterButton" onClick={() => setMobileOpen(true)}>☷ فیلترها <span>تنظیم نتایج</span></button>{mobileOpen && <button className="filterBackdrop" aria-label="بستن فیلتر" onClick={() => setMobileOpen(false)} />}<aside className={`filters ${mobileOpen ? "open" : ""}`}><div className="filterTitle"><div><span>فیلتر هوشمند</span><b>انتخاب دقیق‌تر</b></div><button onClick={() => setMobileOpen(false)}>×</button></div><form onSubmit={apply}><label>عبارت جستجو<input name="search" defaultValue={params.search || ""} placeholder="نام، مدل یا SKU" /></label><label>دسته‌بندی<select name="category" defaultValue={params.category || ""}><option value="">همه دسته‌ها</option>{categories.map(c => <option key={c.id} value={c.slug}>{c.name} ({c.product_count || 0})</option>)}</select></label><label>برند<select name="brand" defaultValue={params.brand || ""}><option value="">همه برندها</option>{brands.map(b => <option key={b.id} value={b.slug}>{b.name}</option>)}</select></label><span className="filterLabel">محدوده قیمت</span><div className="priceFields"><input aria-label="حداقل قیمت" name="min_price" type="number" defaultValue={params.min_price || ""} placeholder="از قیمت" /><input aria-label="حداکثر قیمت" name="max_price" type="number" defaultValue={params.max_price || ""} placeholder="تا قیمت" /></div><label>حداقل امتیاز<select name="rating" defaultValue={params.rating || ""}><option value="">همه امتیازها</option><option value="4">۴ ستاره به بالا</option><option value="3">۳ ستاره به بالا</option></select></label><div className="filterChecks"><label className="check"><input type="checkbox" name="availability" value="true" defaultChecked={params.availability === "true"} /><span></span> فقط کالاهای موجود</label><label className="check"><input type="checkbox" name="discount" value="true" defaultChecked={params.discount === "true"} /><span></span> فقط تخفیف‌دارها</label></div><button className="button primary">نمایش نتایج</button><button type="button" className="clearFilters" onClick={clear}>پاک کردن همه فیلترها</button></form></aside><div className="sortBar"><span>مرتب‌سازی:</span>{[["-created_at","جدیدترین"],["base_price","ارزان‌ترین"],["-base_price","گران‌ترین"],["-sold_count","پرفروش‌ترین"],["-discount_percent_sort","بیشترین تخفیف"]].map(([value,label]) => <button className={params.ordering === value ? "active" : ""} key={value} onClick={() => sort(value)}>{label}</button>)}</div></>;
}
