"use client";
import { useState } from "react";
import type { Product } from "../lib/types";
import { API_URL, formatPrice } from "../lib/api";

export default function ProductCard({ product, index = 0 }: { product: Product; index?: number }) {
  const [message, setMessage] = useState(""); const [favorite, setFavorite] = useState(false);
  async function add() { const token = localStorage.getItem("access_token"); if (!token) { location.href = `/login?next=/product/${product.slug}`; return; } try { const detail = await fetch(`${API_URL}/products/${product.slug}/`).then(r => r.json()) as Product; const variant = detail.variants?.find(v => v.stock > 0); if (!variant) throw new Error(); const response = await fetch(`${API_URL}/cart/add/`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ product: product.id, variant: variant.id, quantity: 1 }) }); if (!response.ok) throw new Error(); setMessage("به سبد اضافه شد ✓"); } catch { setMessage("افزودن به سبد ممکن نشد"); } setTimeout(() => setMessage(""), 2500); }
  return <article className="productCard revealCard" style={{ "--delay": `${Math.min(index, 7) * 70}ms` } as React.CSSProperties}><a href={`/product/${product.slug}`} className="productArt"><div className="imageGlow"></div>{product.primary_image ? <img src={product.primary_image} alt={product.name} loading="lazy" /> : <span className="productShape">✦</span>}<div className="productBadges">{product.discount_percent > 0 && <small className="discountBadge">٪{product.discount_percent}</small>}{product.is_new && <small className="newBadge">جدید</small>}</div><span className={`stockDot ${product.total_stock ? "" : "off"}`}>{product.total_stock ? "موجود" : "ناموجود"}</span></a><button className={`favoriteButton ${favorite ? "active" : ""}`} onClick={() => setFavorite(v => !v)} aria-label="افزودن به علاقه‌مندی">{favorite ? "♥" : "♡"}</button><div className="productInfo"><div className="cardMeta"><span>{product.brand.name}</span><span className="stars">★ {product.average_rating || "۴.۸"}</span></div><a href={`/product/${product.slug}`}><h3>{product.name}</h3></a><p>{product.short_description}</p><div className="cardPrice">{product.compare_at_price && <del>{formatPrice(product.compare_at_price)}</del>}<strong>{formatPrice(product.base_price)}</strong></div><button className="addButton" onClick={add}><span>＋</span> افزودن به سبد</button>{message && <span className="miniToast">{message}</span>}</div></article>;
}
