# Generated by Django 5.2.5 on 2026-08-21 12:45

import apps.catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_logo_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='external_url',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.catalog.models.validate_image_size]),
        ),
    ]
